install nodejs  in ubuntu:16.04  image docker
UnResident3/docker-research pull request #2
Opened 2019-11-08 07:05 UTC by TanooKacha

เริ่มเรียนรู้การติดตั้ง nodejs ใน  docker ubuntu

2019-11-08 12:34 UTC, fanneiOZ requested changes
ไปทำ soft reset โฟลเดอร์ `/nginx-v2` ออกจาก branch นี้ แล้ว ย้ายไปใส่ commit on top `feature\thesis-111` แทน

- [x] 1) Soft Reset 1 Commit
- [x] 2) Commit เฉพาะ ไฟล์ `command/ubuntu-nodejs.sh` เพียงแค่ไฟล์เดียว เพราะต้องการแค่นี้
- [x] 3) Commit ทุกอย่างใน `\nginx-v2\*` แยกออกไปเป็นอีก 1 commit
- [x] 4) Cherrypick Commit จาก #4 ไปไว้ on top `feature\thesis-111`
- [x] 5) Hard Reset 1 Commit ใน `feature\thesis-128` เพื่อเอา Commit ของ #3 ออกไป

2019-11-08 12:34 UTC, fanneiOZ commented on ubt16.04/Dockerfile
> +FROM ubuntu:16.04
ถ้าจะตั้งต้น แค่เพื่อสร้าง container จาก `ubuntu:16.04` ดั้งเดิมต้นฉบับ ก็ไม่ควรจะต้องมานั่งเขียน Dockerfile แบบนี้ เสียเวลาเปล่า แค่รันคำสั่ง
```
$> docker run --name ubt1604 -d ubuntu:16.04 
```
ก็พอแล้ว ไฟล์นี้ไม่จำเป็นอะไรเลยยยยยยยยยยย

- [ ] เอา Dockerfile อันนี้ออกไปให้พ้น ไม่จำเป็น!!!!! ไม่มีใครเขาทำกัน

2019-11-08 12:44 UTC, fanneiOZ reviewed
เดี๋ยวมาเช็คประเด็นของ Step 5 & 6 ร่วมกัน

2019-11-09 06:34 UTC, TanooKacha commented on ubt16.04/Dockerfile
> +FROM ubuntu:16.04
มันเป็นความผิดพลาดอยากจะเพราะยังไม่เข้าใจตอนนั้น

2019-11-18 13:30 UTC, fanneiOZ approved these changes

2019-11-18 13:32 UTC, fanneiOZ commented
สุดท้ายก็มาเล่นกันง่ายๆ ขิงๆ โดยที่ @TanooKacha  รู้จักการ bind mount / WORKDIR / CMD สรุปคือรู้อะไรที่เป็นประโยชน์มากขึ้น รวมถึงเทคนิคการใช้ Chained RUN ใน Dockerfile

2019-11-18 13:44 UTC, fanneiOZ approved these changes

2019-11-18 13:44 UTC, merged